# Generated by Django 4.1.1 on 2022-10-06 16:21
# Generated by Django 4.1.2 on 2022-10-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('co2e', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('co2e_min', models.FloatField()),
                ('co2e_max', models.FloatField()),
                ('co2e_med', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=False)),
                ('custom_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.customingredient')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
                ('upload_image_of_ingredients', models.ImageField(default='', upload_to='main_app/static/uploads/')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('method', models.CharField(default='', max_length=300)),
                ('public', models.BooleanField(default=False)),
                ('custom_ingredients', models.ManyToManyField(blank=True, through='main_app.IngredientQuantity', to='main_app.customingredient')),
                ('ingredients', models.ManyToManyField(blank=True, through='main_app.IngredientQuantity', to='main_app.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
        ),
    ]
