# Generated by Django 4.1.2 on 2022-10-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='upload_image_of_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbon_calculation',
            field=models.FloatField(default=False, null=True),
        ),
    ]
