# Generated by Django 4.1.1 on 2022-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing2',
        ),
    ]
