# Generated by Django 4.1.2 on 2022-10-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_recipe_upload_image_of_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
