# Generated by Django 4.1.1 on 2022-10-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_remove_recipe_ing1_remove_recipe_ing2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='upload_image_of_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ing',
        ),
    ]
