# Generated by Django 4.1.2 on 2022-10-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customingredient',
            name='co2e',
            field=models.FloatField(null=True),
        ),
    ]
