# Generated by Django 4.1.2 on 2022-10-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_user_email'),
        ('main_app', '0003_alter_recipe_method'),
    ]

    operations = [
    ]
