# Generated by Django 4.1.2 on 2022-10-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_customingredient_co2e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='custom_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.customingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.ingredient'),
        ),
    ]
