# Generated by Django 4.1.1 on 2022-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customingredient',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergy',
        ),
        migrations.AddField(
            model_name='recipe',
            name='custom_ingredients',
            field=models.ManyToManyField(to='main_app.customingredient'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
