# Generated by Django 4.1.2 on 2022-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ingredientquantity_custom_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='custom_ingredients',
            field=models.ManyToManyField(null=True, through='main_app.IngredientQuantity', to='main_app.customingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, through='main_app.IngredientQuantity', to='main_app.ingredient'),
        ),
    ]
